Repository dzikus13/league, pull requests merged in 2022-05, with the labels that each got.

#33 Issue #10 goal scoring fixes
  league/manager/admin.py
  league/manager/models.py
  league/manager/views.py
Labels: help wanted

#39 Update models.py, league_winner got changes
  league/manager/models.py
Labels: enhancement, backend

#40 Goal scoring fixes
  league/manager/models.py
Labels: enhancement, backend

#43 Quality of life changes
  league/manager/models.py
Labels: enhancement, backend

#44 Generic views
  .gitignore
  .idea/.gitignore
  league/league/settings.py
  league/league/urls.py
  league/manager/admin.py
  league/manager/migrations/0001_initial.py
  league/manager/migrations/__init__.py
  league/manager/static/css/style.css
  league/manager/templates/manager/add_forms.html
  league/manager/templates/manager/base.html
  league/manager/templates/manager/error.html
  league/manager/templates/manager/event_details.html
  league/manager/templates/manager/event_type_details.html
  league/manager/templates/manager/event_types.html
  league/manager/templates/manager/events.html
  league/manager/templates/manager/league_details.html
  league/manager/templates/manager/leagues.html
  league/manager/templates/manager/main.html
  league/manager/templates/manager/manager.html
  league/manager/templates/manager/match_details.html
  league/manager/templates/manager/matches.html
  league/manager/templates/manager/player_details.html
  league/manager/templates/manager/players.html
  league/manager/templates/manager/team_details.html
  league/manager/templates/manager/teams.html
  league/manager/tests.py
  league/manager/urls.py
  league/manager/views.py
Labels: enhancement, frontend

#50 Added new validation options
  league/manager/models.py
Labels: enhancement, question, backend

#49 PROPOSAL: Name changes
  league/manager/admin.py
  league/manager/models.py
  league/manager/tests.py
Labels: question

#54 Poprawa logiki strony oraz ufunkcjonowanie formularzy
  league/manager/admin.py
  league/manager/forms.py
  league/manager/models.py
  league/manager/static/css/style.css
  league/manager/static/css/style13.css
  league/manager/templates/manager/add_event.html
  league/manager/templates/manager/add_forms.html
  league/manager/templates/manager/add_league.html
  league/manager/templates/manager/add_match.html
  league/manager/templates/manager/add_player.html
  league/manager/templates/manager/add_team.html
  league/manager/templates/manager/base.html
  league/manager/templates/manager/error.html
  league/manager/templates/manager/event_details.html
  league/manager/templates/manager/event_type_details.html
  league/manager/templates/manager/event_types.html
  league/manager/templates/manager/events.html
  league/manager/templates/manager/league_details.html
  league/manager/templates/manager/leagues.html
  league/manager/templates/manager/logged.html
  league/manager/templates/manager/logged_out.html
  league/manager/templates/manager/login.html
  league/manager/templates/manager/main.html
  league/manager/templates/manager/manager.html
  league/manager/templates/manager/match_details.html
  league/manager/templates/manager/matches.html
  league/manager/templates/manager/player_details.html
  league/manager/templates/manager/players.html
  league/manager/templates/manager/register.html
  league/manager/templates/manager/registered.html
  league/manager/templates/manager/team_details.html
  league/manager/templates/manager/teams.html
  league/manager/templates/manager/user_profile.html
  league/manager/templates/manager/users.html
  league/manager/templatetags/custom_tags.py
  league/manager/urls.py
  league/manager/views.py
Labels: enhancement, frontend

#53 User_management - judge control
  league/manager/templatetags/__init__.py
  league/manager/templatetags/user_management.py
Labels: enhancement, backend
